{"name": "test_mp_login[woshi-lallalallala-数据库]", "status": "broken", "statusDetails": {"message": "NameError: name 'allure' is not defined", "trace": "self = <scripts.test_02_mp_article.TestMpLogin object at 0x10cc81a90>\ntitle = 'woshi', content = 'lallalallala', click_text = '数据库'\n\n    @pytest.mark.parametrize(\"title, content, click_text\", readyaml(\"mp_article.yml\"))\n    def test_mp_login(self, title, content, click_text):\n    \n        try:\n            # 调用登录业务方法\n            self.article.page_mp_articel(title, content, click_text)\n            # 断言\n>           assert expect == self.article.page_get_info()\nE           NameError: name 'expect' is not defined\n\ntest_02_mp_article.py:40: NameError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_02_mp_article.TestMpLogin object at 0x10cc81a90>\ntitle = 'woshi', content = 'lallalallala', click_text = '数据库'\n\n    @pytest.mark.parametrize(\"title, content, click_text\", readyaml(\"mp_article.yml\"))\n    def test_mp_login(self, title, content, click_text):\n    \n        try:\n            # 调用登录业务方法\n            self.article.page_mp_articel(title, content, click_text)\n            # 断言\n            assert expect == self.article.page_get_info()\n        except  Exception as e:\n            print(\"错误原因\", e)\n>           self.article.base_get_img()\n\ntest_02_mp_article.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../base/base.py:68: in base_get_img\n    self.__base_write_img(file_path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_article.PageMpArticle object at 0x10d552f50>\nfile_path = '/Users/lq/python/test/2020-09/uiAutoTestHmtt/image/20200911201037_.png'\n\n    def __base_write_img(self, file_path):\n        with open(file_path, \"rb\") as f:\n            file = f.read()\n>           allure.attach(\"错误原因\", file, allure.attach_type.PNG)\nE           NameError: name 'allure' is not defined\n\n../base/base.py:73: NameError"}, "attachments": [{"name": "log", "source": "3feff79f-d90c-477b-a2e2-b295d1924872-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "title", "value": "'woshi'"}, {"name": "content", "value": "'lallalallala'"}, {"name": "click_text", "value": "'数据库'"}], "start": 1599826227767, "stop": 1599826237836, "uuid": "f080cfa8-36b0-4afc-ac03-8864d3d29bb0", "historyId": "360d0698737556c219b2cf57316b6569", "testCaseId": "9b66674a365236be33f83214238d0445", "fullName": "scripts.test_02_mp_article.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_02_mp_article"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "promote.cache-dns.local"}, {"name": "thread", "value": "53929-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_02_mp_article"}]}